name: Isobelle
favicon: null
layout_spectrum: 0.9764603897929192
typography_spectrum: 0.047312864335253835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6262062590103596
  lightness: 0.6652707832399756
  saturation: 0.6157398668583483
  rhythmicContrast: 0.5644222025293857
purpose: []
